#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_MPU6050.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_TMP117.h>
#include "MAX30100_PulseOximeter.h"

#include "config.h"
#include "ble_service.h"

// -------------------------------------------------------------
// TinyML Model Integration (Generated by Edge Impulse Studio)
// -------------------------------------------------------------
// Replace with your exported Edge Impulse C++ library header:
// #include <MatriSense_inferencing.h> 

// Sensor Objects
PulseOximeter pox;
Adafruit_MPU6050 mpu;
Adafruit_TMP117 tmp117;

// System State Flags
bool poxOK = false;
bool mpuOK = false;
bool tmpOK = false;

// -------------------------------------------------------------
// TinyML Sliding Window Buffer
// Sampling Rate: 50 Hz | Window Size: 2.0 Seconds = 100 Samples
// Frame Structure per sample: [AccelX, AccelY, AccelZ, HR, SpO2, Temp]
// -------------------------------------------------------------
#define FEATURE_COUNT_PER_SAMPLE 6
#define WINDOW_SAMPLES           100
#define TOTAL_DSP_INPUT_SIZE     (FEATURE_COUNT_PER_SAMPLE * WINDOW_SAMPLES)

static float featuresBuffer[TOTAL_DSP_INPUT_SIZE];
static uint16_t bufferIndex = 0;

// Function Declarations
void initSensors();
uint8_t runTinyMLInference();
void handleAlerts(uint8_t alertStatus);

void setup() {
    Serial.begin(SERIAL_BAUD_RATE);
    
    // Configure Buzzer GPIO
    pinMode(PIN_BUZZER, OUTPUT);
    digitalWrite(PIN_BUZZER, LOW);

    // Initialize I2C Bus & Wireless BLE Stack
    Wire.begin();
    initBLE();
    startAdvertising();

    // Initialize Onboard Hardware Sensors
    initSensors();
}

void loop() {
    // MAX30100 PPG sampling must run continuously
    if (poxOK) {
        pox.update();
    }

    // High-frequency sensor collection loop (50 Hz / 20 ms interval for TinyML buffer)
    static uint32_t lastSampleTime = 0;
    if (millis() - lastSampleTime >= 20) { 
        lastSampleTime = millis();

        // 1. Collect Real-Time Data Streams
        uint8_t heartRate = poxOK ? pox.getHeartRate() : 0;
        uint8_t spO2 = poxOK ? pox.getSpO2() : 0;

        sensors_event_t accelEvt, gyroEvt, tempEvt;
        if (mpuOK) {
            mpu.getEvent(&accelEvt, &gyroEvt, &tempEvt);
        }

        sensors_event_t skinTempEvt;
        float bodyTemp = 0.0;
        if (tmpOK) {
            tmp117.getEvent(&skinTempEvt);
            bodyTemp = skinTempEvt.temperature;
        }

        // 2. Append Sample to Sliding TinyML Input Window
        if (bufferIndex < TOTAL_DSP_INPUT_SIZE) {
            featuresBuffer[bufferIndex++] = accelEvt.acceleration.x;
            featuresBuffer[bufferIndex++] = accelEvt.acceleration.y;
            featuresBuffer[bufferIndex++] = accelEvt.acceleration.z;
            featuresBuffer[bufferIndex++] = (float)heartRate;
            featuresBuffer[bufferIndex++] = (float)spO2;
            featuresBuffer[bufferIndex++] = bodyTemp;
        }

        // 3. When Sliding Window is Full (Every 2.0 Seconds), Run Inference
        if (bufferIndex >= TOTAL_DSP_INPUT_SIZE) {
            
            // Run Edge AI Inference
            uint8_t alertStatus = runTinyMLInference();

            // Sound Alarm in Real-Time Based on Anomaly Prediction
            handleAlerts(alertStatus);

            // Construct and Stream BLE Packet over the Air
            VitalsPacket packet;
            packet.heartRate = heartRate;
            packet.spO2 = spO2;
            packet.temperature = (int16_t)(bodyTemp * 100.0f);
            packet.accelX = (int8_t)(accelEvt.acceleration.x * 10.0f);
            packet.accelY = (int8_t)(accelEvt.acceleration.y * 10.0f);
            packet.accelZ = (int8_t)(accelEvt.acceleration.z * 10.0f);
            packet.alertStatus = alertStatus;

            sendVitalsNotification(packet);

            // Reset Buffer for Next Window Cycle
            bufferIndex = 0; 
        }
    }
}

// -------------------------------------------------------------
// On-Device TinyML Inference Engine Function
// -------------------------------------------------------------
uint8_t runTinyMLInference() {
    /* 
     * Edge Impulse Integration Execution Pattern:
     * 
     * signal_t signal;
     * int err = numpy::signal_from_buffer(featuresBuffer, TOTAL_DSP_INPUT_SIZE, &signal);
     * 
     * ei_impulse_result_t result = { 0 };
     * EI_IMPULSE_ERROR res = run_classifier(&signal, &result, false);
     * 
     * float anomalyScore = result.anomaly; // Returns 0.0 to 1.0 confidence score
     */

    // Placeholder simulated score for testing prior to flashing Edge Impulse C++ zip:
    float anomalyScore = 0.15f; 

    // Anomaly Triaging Logic
    if (anomalyScore > 0.70f) {
        Serial.println("[TinyML Alert] Critical Physiological Anomaly Detected!");
        return 2; // Red Alert
    } else if (anomalyScore > 0.35f) {
        Serial.println("[TinyML Caution] Moderate Deviation Observed.");
        return 1; // Yellow Alert
    }

    return 0; // Green / Safe
}

void initSensors() {
    Serial.println("Initializing MatriSense Sensors for TinyML Pipeline...");

    if (pox.begin()) poxOK = true;
    if (mpu.begin(I2C_ADDR_MPU6050)) {
        mpuOK = true;
        mpu.setAccelerometerRange(MPU6050_RANGE_2_G);
    }
    if (tmp117.begin(I2C_ADDR_TMP117)) tmpOK = true;
}

void handleAlerts(uint8_t alertStatus) {
    if (alertStatus == 2) {
        // Red Alert: High-pitched urgent double siren pulse
        tone(PIN_BUZZER, TONE_ALARM_FREQ_HZ, 250);
        delay(300);
        tone(PIN_BUZZER, TONE_ALARM_FREQ_HZ, 250);
    } else if (alertStatus == 1) {
        // Yellow Alert: Soft warning chime
        tone(PIN_BUZZER, TONE_WARN_FREQ_HZ, 150);
    } else {
        noTone(PIN_BUZZER);
    }
}
