; ==========================================================
; MatriSense Firmware PlatformIO Configuration
; Target MCU: Nordic Semi nRF52840 (Pro Micro / nice!nano v2)
; ==========================================

[env:nicenano]
platform = nordicnrf52@10.2.0
board = nicenano
framework = arduino

; Serial Monitor & Upload Options
monitor_speed = 115200
upload_protocol = nrfutil

; Compiler Flags for ARM Cortex-M4 Hardware Floating Point Unit
build_flags = 
    -D NRF52840_XXAA
    -D CONFIG_NFCT_PINS_AS_GPIOS
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16

; External Library Dependencies (Auto-installed by PlatformIO)
lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit TMP117 @ ^1.0.3
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    https://github.com/oxullo/Arduino-MAX30100.git#1.2.1
